export const elements = {
  modeSelector: document.getElementById('mode-selector') as HTMLDivElement,
  lessonsContainer: document.getElementById('lessons-container') as HTMLDivElement,
  practiceContainer: document.getElementById('practice-container') as HTMLDivElement,
  challengesContainer: document.getElementById('challenges-container') as HTMLDivElement,
  newPuzzleButton: document.getElementById('new-puzzle-button') as HTMLButtonElement,
  boardEl: document.getElementById('board') as HTMLDivElement,
  messageArea: (document.getElementById('message-area') as HTMLDivElement).querySelector('h2') as HTMLHeadingElement,
  gameInfo: document.getElementById('game-info') as HTMLDivElement,
  geminiOutput: document.getElementById('gemini-output') as HTMLDivElement,
  geminiLoading: document.getElementById('gemini-loading') as HTMLDivElement,
  geminiContent: document.getElementById('gemini-content') as HTMLDivElement,
  lessonProgressNav: document.getElementById('lesson-progress-nav') as HTMLDivElement,
  completionDialog: document.getElementById('completion-dialog') as HTMLDivElement,
  dialogTitle: document.getElementById('dialog-title') as HTMLHeadingElement,
  dialogMessage: document.getElementById('dialog-message') as HTMLParagraphElement,
  dialogButtons: document.getElementById('dialog-buttons') as HTMLDivElement,
  authContainer: document.getElementById('auth-container') as HTMLDivElement,
  practiceModeButton: document.getElementById('practice-mode-button') as HTMLButtonElement,
  challengesModeButton: document.getElementById('challenges-mode-button') as HTMLButtonElement,
  lockIconPractice: document.getElementById('lock-icon-practice') as HTMLSpanElement,
  prevChallengeButton: document.getElementById('prev-challenge-button') as HTMLButtonElement,
  nextChallengeButton: document.getElementById('next-challenge-button') as HTMLButtonElement,
  challengeDayDisplay: document.getElementById('challenge-day-display') as HTMLDivElement,
  closeDialogButton: document.getElementById('close-dialog-button') as HTMLButtonElement,
};